// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"time"
)

type Comment struct {
	CommentID       int64
	CreatedByUserID int64
	PostID          int64
	Comment         string
	CreatedAt       time.Time
}

type Follower struct {
	UserID         int64
	FollowedUserID int64
}

type Post struct {
	PostID          int64
	CreatedByUserID int64
	Caption         string
	CreatedAt       time.Time
}

type PostLike struct {
	PostID    int64
	PostLiker string
}

type PostMedium struct {
	MediaID   int64
	PostID    int64
	MediaFile string
	CreatedAt time.Time
}

type User struct {
	UserID            int64
	ProfilePicture    string
	Username          string
	FullName          string
	HashedPassword    string
	Email             string
	PasswordChangedAt time.Time
	CreatedAt         time.Time
}
