// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"context"
)

type Querier interface {
	CountPostTotalLikes(ctx context.Context, postID int64) ([]int64, error)
	CountUserTotalFollower(ctx context.Context, userID int64) ([]int64, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateFollower(ctx context.Context, arg CreateFollowerParams) (Follower, error)
	CreateMedia(ctx context.Context, arg CreateMediaParams) (PostMedium, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreatePostLikes(ctx context.Context, arg CreatePostLikesParams) (PostLike, error)
	CreatePostUnlikes(ctx context.Context, postLiker string) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteComment(ctx context.Context, commentID int64) error
	DeleteFollower(ctx context.Context, followedUserID int64) error
	DeletePost(ctx context.Context, postID int64) error
	GetComment(ctx context.Context, commentID int64) (Comment, error)
	GetMedia(ctx context.Context, postID int64) (PostMedium, error)
	GetPost(ctx context.Context, postID int64) (Post, error)
	GetPostLike(ctx context.Context, arg GetPostLikeParams) (PostLike, error)
	GetUser(ctx context.Context, username string) (User, error)
	GetUserFollower(ctx context.Context, arg GetUserFollowerParams) (Follower, error)
	ListComment(ctx context.Context, arg ListCommentParams) ([]Comment, error)
	ListFollower(ctx context.Context, arg ListFollowerParams) ([]Follower, error)
	ListPost(ctx context.Context, arg ListPostParams) ([]Post, error)
	ListPostLiker(ctx context.Context, arg ListPostLikerParams) ([]PostLike, error)
}

var _ Querier = (*Queries)(nil)
